### ISSUE TITLE
return sampled aggregations for large responses

### ISSUE THREAD

**Issue by elipapa** [opentargets/library-api#2]
- either make the aggs conditional, so that you can choose which one to run
- or make a count of the hits, if they are > 1M you put a sampler aggs in front of these aggs

in the meantime the webapp (cc @LucaFumis ) will do two calls: one to get papers and then another to get aggs/chips. That way the user does not see the spinning wheel of death.

**Comment by apierleoni** [comment]
as in the platform, it is always recommended to make a call to get the data, and a separate call (with size=0) to get the agg data.
This allows for the real data to come quickly, and the aggs to pop up when/if available.

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/library #27](https://github.com/opentargets/library/issues/27) via [**ZenHub**](https://www.zenhub.com/)
